- src/administrator/models/forms/eventticket.xml
- src/administrator/sql/install.mysql.utf8.sql
- src/administrator/sql/updates/mysql/0.1.sql
- src/administrator/views/eventticket/tmpl/edit.php
- src/site/models/ticketpurchase.php
- src/site/views/ticketpurchase/tmpl/default.php
Maybe wait till I have fixed the padding in the template to merge this?
Fixes #133.
> added notes field to event tickets

- src/site/models/ticketpurchase.php
- src/site/views/ticketpurchase/tmpl/default.php
Did a rebase.... hope I did it right!
Fixes #158
> Adding more info to why members can't buy a ticket.

- src/site/ModelList.php
- src/site/models/universityeventattendees.php
- src/site/views/universityeventattendees/tmpl/default.php
- src/site/views/universitymembers/tmpl/committee.php
- src/site/views/universitymembers/tmpl/default.php
- src/site/views/universitymembers/tmpl/graduated.php
- src/site/views/universitymembers/tmpl/pending.php
Not sure if this is the correct way to do this but I'm sure you'll let me know if not! ;)
Fixes #121 .
> Show the actual university name in Event Attendees & University Members views.

- src/site/models/event.php
> Fixed ticket sales on Future Events page not always displaying correctly

- src/site/models/ticketpurchase.php
- src/site/views/ticketpurchase/tmpl/default.php
> Reworked ticket purchase query and added why you can't buy a ticket

- src/administrator/models/forms/universitymember.xml
- src/site/ModelItem.php
- src/site/models/event.php
- src/site/views/event/tmpl/future.php
- src/site/views/event/tmpl/past.php
> Allow hosts of events to view ticket sales.

- src/administrator/models/forms/committeemember.xml
- src/administrator/models/forms/competition.xml
- src/administrator/models/forms/damage.xml
- src/administrator/models/forms/deposit.xml
- src/administrator/models/forms/event.xml
- src/administrator/models/forms/eventhost.xml
- src/administrator/models/forms/eventregistration.xml
- src/administrator/models/forms/eventticket.xml
- src/administrator/models/forms/grant.xml
- src/administrator/models/forms/individualresult.xml
- src/administrator/models/forms/member.xml
- src/administrator/models/forms/qualification.xml
- src/administrator/models/forms/teamresult.xml
- src/administrator/models/forms/ticket.xml
- src/administrator/models/forms/universitymember.xml
Newest members now show at the top of dropdown lists.
Most recent events, competition and  ticket types now show at the top of dropdown lists.
> Reworked dropdown box ordering

- src/administrator/models/eventregistrations.php
- src/administrator/views/eventregistrations/tmpl/default.php
- src/administrator/views/eventregistrations/view.html.php
Added University column, fixed ordering & improved searching
Fixes #117
> Fixed & improved Event Registrations in Admin Section

- src/site/models/seasonresults.php
Set $seasonId to this year and fix query that wasn't using the $seasonId variable
> Increment $seasonId to this year

- src/administrator/sql/install.mysql.utf8.sql
- src/administrator/sql/updates/mysql/0.1.sql
> Add unique constraint to university_member table

- src/site/controllers/memberpayment.php
- src/site/controllers/ticketpurchase.php
- src/site/swa.php
- src/site/views/memberpayment/tmpl/default.php
- src/site/views/ticketpurchase/tmpl/default.php
**Don't merge just yet!** Need to discuss where we should put the Stripe PHP lib and the Stripe API config with public and secret keys - obv public version control is not the place for them!
> Implemented the new Stripe payment system

- src/administrator/sql/install.mysql.utf8.sql
- src/administrator/sql/updates/mysql/0.1.sql
- src/site/controllers/ticketpurchase.php
- src/site/models/ticketpurchase.php
- src/site/views/ticketpurchase/tmpl/default.php
- src/site/views/ticketpurchase/tmpl/summary.php
- src/site/views/ticketpurchase/tmpl/terms.php
Still need to write the T&C in an article and specify the correct ARTICLE_ID.
> Added T&C and T-Shirt Size

- src/site/views/universitymembers/tmpl/committee.php
- src/site/views/universitymembers/tmpl/default.php
- src/site/views/universitymembers/tmpl/graduated.php
- src/site/views/universitymembers/tmpl/pending.php
- Only show "register for [event]" if event is open.
- Increase readability of the different views.
> Improve club

- src/site/controllers/memberpayment.php
- src/site/controllers/ticketpurchase.php
Added extra checks and logging.
> Fix payments

- src/administrator/models/eventtickets.php
- src/administrator/models/forms/eventticket.xml
- src/administrator/views/eventticket/tmpl/edit.php
- src/administrator/views/eventtickets/tmpl/default.php
- src/site/models/ticketpurchase.php
Reworked logic for who can see and buy tickets.
Updated in both the front and the back end.
Probably good idea to pull this locally and test it as it could really mess ticket purchasing up!
Do a squash and merge on this one due to all my "Work in progress"!
> Ticket details

- adminer/Dockerfile
- docker-compose.yml
- src/administrator/models/forms/eventticket.xml
- src/site/models/ticketpurchase.php
Enable developing in docker containers
> Docker dev

- src/site/SwaModelMemberTrait.php
- tests/browser/ClubEventAttendeesTest.php
- tests/browser/LoginAndMenuTest.php
- tests/browser/SWABrowserTestCase.php
- tests/browser/traits/LoginTrait.php
> Fix #231, universityeventattendees undefined university_name

- .docker/db/initdb/init.sql
- src/administrator/models/forms/member.xml
- src/administrator/sql/install.mysql.utf8.sql
- src/administrator/sql/updates/mysql/0.1.sql
- src/administrator/views/member/tmpl/edit.php
- src/site/controllers/memberdetails.php
- src/site/models/forms/memberdetails.xml
- src/site/models/forms/memberregistration.xml
- src/site/views/memberdetails/tmpl/default.php
- src/site/views/memberregistration/tmpl/default.php
Small modifications to the forms
No longer collect t-shirt size as this is done on ticket purchase
Slight modifications to existing form fields for increased inclusion
> Changes to Sign-up/Membership form

- .docker/db/initdb/init.sql
- docker-compose.yml
- docs/event_ticket.rst
- src/administrator/models/forms/eventticket-example.json
- src/administrator/models/forms/eventticket.xml
- src/administrator/models/forms/member.xml
- src/administrator/sql/install.mysql.utf8.sql
- src/administrator/sql/updates/mysql/0.1.sql
- src/administrator/views/member/tmpl/edit.php
- src/site/controllers/memberdetails.php
- src/site/models/event.php
- src/site/models/forms/memberdetails.xml
- src/site/models/forms/memberregistration.xml
- src/site/models/seasonresults.php
- src/site/models/ticketpurchase.php
- src/site/views/memberdetails/tmpl/default.php
- src/site/views/memberregistration/tmpl/default.php
- src/site/views/seasonresults/tmpl/default.php
- src/site/views/seasonresults/view.html.php
- Changed any use of sex to gender on the site
- Changed whitelist to allowed
- Changed blacklist to denied
> Gender // Whitelist and Blacklist changes

- src/site/controllers/memberpayment.php
There was a mistake in the if statements, it was assigning rather than comparing. The returned price in the intent was also fixed
> Pricing Fix
